### ISSUE TITLE
Maven Compiler 3.10.0 creates invalid 'package-info.class' on Windows

### ISSUE THREAD

**Issue by turbanoff** [eclipse-aspectj/aspectj#176]
Recently we got confusing error from AspectJ maven plugin in our project:
```
[INFO] --- aspectj-maven-plugin:1.12.6:compile (default) @ dxServerFoundation ---
[INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[ERROR] can't determine annotations of missing type com\devexperts\dxcore\api\script\package-info
when processing declare parents com\devexperts\dxcore\api\script\package-info
when weaving intertype declarations com\devexperts\dxcore\api\script\package-info
when batch building BuildConfig[null] #Files=131 AopXmls=#0
 [Xlint:cantFindType]
        <unknown source file>:<no line information>

[ERROR] can't determine implemented interfaces of missing type com\devexperts\dxcore\api\script\package-info
when processing declare parents com\devexperts\dxcore\api\script\package-info
when weaving intertype declarations com\devexperts\dxcore\api\script\package-info
when batch building BuildConfig[null] #Files=131 AopXmls=#0
 [Xlint:cantFindType]
        <unknown source file>:<no line information>

[ERROR] can't determine implemented interfaces of missing type com\devexperts\dxcore\api\script\package-info
when processing declare parents com\devexperts\dxcore\api\script\package-info
when weaving intertype declarations com\devexperts\dxcore\api\script\package-info
when batch building BuildConfig[null] #Files=131 AopXmls=#0
 [Xlint:cantFindType]
        <unknown source file>:<no line information>

[ERROR] can't determine modifiers of missing type com\devexperts\dxcore\api\script\package-info
when weaving intertype declarations com\devexperts\dxcore\api\script\package-info
when batch building BuildConfig[null] #Files=131 AopXmls=#0
 [Xlint:cantFindType]
        <unknown source file>:<no line information>
```
It seems that AspectJ tries to resolve interfaces of `package-info` and fails to do that.
I believe AspectJ shouldn't touch package-info.

How we invoke plugin:
```
<build>
    <plugins>
        <plugin>
            <groupId>com.nickwongdev</groupId>
            <artifactId>aspectj-maven-plugin</artifactId>
            <configuration>
                <aspectLibraries>
                    <aspectLibrary>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-aspects</artifactId>
                    </aspectLibrary>
                </aspectLibraries>
            </configuration>
            <executions>
                <execution>
                    <goals>
                        <goal>compile</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```

**Comment by kriegaex** [comment]
Andrey, I am very busy. Please help me by providing an [MCVE](https://stackoverflow.com/help/mcve). These days, I do not have the cycles to prepare one by myself. Just post a link to a reproducer here on GitHub. Thank you so much.

**Comment by turbanoff** [comment]
Attached minimal project. To reproduce just run `mvn clean verify`
[dxcore-temp.zip](https://github.com/eclipse/org.aspectj/files/9188154/dxcore-temp.zip)
Fails for me with
```
INFO] --- aspectj-maven-plugin:1.12.6:compile (default) @ server ---
[INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[ERROR] can't determine modifiers of missing type some\org\client\package-info
when weaving intertype declarations some\org\client\package-info
when processing compilation unit D:\temp\dxcore-temp\server\src\some\org\server\Runner.java
when batch building BuildConfig[null] #Files=1 AopXmls=#0
 [Xlint:cantFindType]
        <unknown source file>:<no line information>
```

**Comment by kriegaex** [comment]
Thank you, I briefly looked into this and can reproduce the problem. I am not sure yet if it is a problem is AspectJ proper or in AspectJ Maven. ~~The problem seems to be that somehow AJC thinks that `package-info` is a compilation unit, as if it would see the source file. But the `server` module depends on the `client` module in Maven, so I thought it would only see class files. That is the problem, because your sample package info will never yield a class file.~~ 

If you add an annotation with runtime scope to it, e.g.

```java
@Deprecated
package some.org.client;
```

a weavable class file will actually be generated, and AJC compilation passes. So for now, you can use that as a workaround. I will keep you posted if I find out how to fix this (and if so, in which project).

---

**Edit:** Correcting my previous statement, my directory listing in the IDE was not refreshed. Without the annotation, AJC or Javac also create `package-info.class`, but the decompiled result looks like:

```java
// $FF: synthetic class
interface some\org\client\package-info {
}
```

So, now it is pretty clear that AspectJ Maven is not the actual problem but really the AspectJ compiler or weaver itself, which needs to handle package info classes correctly.

**Comment by kriegaex** [comment]
Note to myself:

The annotated package name looks OK in _javap_:

```text
AJ_GH-176\client> javap -c -v target\classes\some\org\client\package-info.class

Classfile AJ_GH-176/client/target/classes/some/org/client/package-info.class
  Last modified 30.07.2022; size 186 bytes
  SHA-256 checksum ad43a307b32f742ad365d80055491bc6f8cb858850d42e691a7375591f905864
  Compiled from "package-info.java"
interface some.org.client.package-info
  minor version: 0
  major version: 55
  flags: (0x1600) ACC_INTERFACE, ACC_ABSTRACT, ACC_SYNTHETIC
  this_class: #1                          // "some/org/client/package-info"
  super_class: #3                         // java/lang/Object
  interfaces: 0, fields: 0, methods: 0, attributes: 2
Constant pool:
  #1 = Class              #2              // "some/org/client/package-info"
  #2 = Utf8               some/org/client/package-info
  #3 = Class              #4              // java/lang/Object
  #4 = Utf8               java/lang/Object
  #5 = Utf8               SourceFile
  #6 = Utf8               package-info.java
  #7 = Utf8               RuntimeVisibleAnnotations
  #8 = Utf8               Ljava/lang/Deprecated;
{
}
SourceFile: "package-info.java"
RuntimeVisibleAnnotations:
  0: #8()
    java.lang.Deprecated
```

But somehow, the non-annotated package name looks weird (backslashes instead of dots) when decompiling the class file:

```text
AJ_GH-176\client> javap -c -v target\classes\some\org\client\package-info.class

Classfile AJ_GH-176/client/target/classes/some/org/client/package-info.class
  Last modified 30.07.2022; size 121 bytes
  SHA-256 checksum 94bf246b6c6af2586493b7b56e5fa3c626e15eb1c731949fa6bea459a2bc28ac
  Compiled from "package-info.java"
interface some\org\client\package-info
  minor version: 0
  major version: 55
  flags: (0x1600) ACC_INTERFACE, ACC_ABSTRACT, ACC_SYNTHETIC
  this_class: #3                          // "some\\org\\client\\package-info"
  super_class: #5                         // java/lang/Object
  interfaces: 0, fields: 0, methods: 0, attributes: 1
Constant pool:
  #1 = Utf8               package-info.java
  #2 = Utf8               some\\org\\client\\package-info
  #3 = Class              #2              // "some\\org\\client\\package-info"
  #4 = Utf8               java/lang/Object
  #5 = Class              #4              // java/lang/Object
  #6 = Utf8               SourceFile
{
}
SourceFile: "package-info.java"
```

**Comment by kriegaex** [comment]
Next finding: Javac - weirdly enough - creates a class name with backslash characters for the package info in the non-annotated case, at least under Windows (probably not on other OS platforms), i.e. the class files are platform-dependent(!!!), which I consider to be a bug in Javac:

```text
interface some\org\client\package-info
```

Whereas in the annotated one, the package name in the class file uses forward slashes as expected (_javap_ decompiles them as dots, though).
```text
interface some.org.client.package-info
```

Manually replacing the 3 backslash characters in the class file by forward slashes using a hex editor, fixes the problem for the subsequent server module compilation.

Interestingly, ECJ (and therefore AJC) use forward slashes in both cases, i.e. their byte code is more platform-independent than Javac's. If first we configure the client to be compiled by ECJ and then use AJC for the server, everything is fine. Anyway, because in this case the client module is compiled by Javac, but the server module is compiled by ACJ, the build fails. BTW, using Javac for client and ECJ for server also works. I.e., by exclusion I found out that the problem is only in ACJ, not in ECJ.

| `client` compiler | `server` compiler | works |
|-|-|-|
| Javac | Javac | yes |
| ECJ | Javac | yes |
| Javac | ECJ | yes |
| ECJ | ECJ | yes |
| Javac | AJC | no ⚡ |
| ECJ | AJC | yes |

Having narrowed down the problem to AJC, I hope I shall soon be able to find the root cause and fix it. But I am not sure if I have enough time to search for it this weekend.

**Comment by kriegaex** [comment]
@turbanoff, please try `1.9.10-SNAPSHOT` from https://oss.sonatype.org/content/repositories/snapshots and report back. Thank you.

**Comment by kriegaex** [comment]
@turbanoff, I would have appreciated some feedback, but I still have news for you: **All my debugging and the workaround in AspectJ were completely unnecessary!**

Just last night I noticed that I could not reproduce the problem with backslash characters in package-info class files when compiling directly with Javac, only with Maven Compiler. That is when I realised, it was totally unrelated to Javac and simply **bug [MCOMPILER-485](https://issues.apache.org/jira/browse/MCOMPILER-485) in plugin version 3.10.0, which is already fixed in 3.10.1.** Simply upgrade the plugin and be happy.

I guess, I can revert the commit in AspectJ. Because I am the only active committer, I might even remove that commit via force-push, even though it probably is going to give @aclement the screaming willies. 😉

I would never have expected the problem to actually be related to the plugin, because the plugin itself normally does not compile anything. But in [MCOMPILER-205](https://issues.apache.org/jira/browse/MCOMPILER-205), someone decided that it was a good idea to actually generate byte code manually in order to create package-info classes instead of simply using `-Xpkginfo:always` on Javac, because by default Javac really does not create those files if there are no runtime annotations on the package, just like I wrote initially, before falsely thinking that I was wrong about it:

> That is the problem, because your sample package info will never yield a class file.

Actually, I was right. By default, Javac does not create one without `-Xpkginfo:always`. The reason Maven Compiler generates it manually is that not all compilers support the option (such as ECJ, but ECJ always generates package info classes by default, unlike Javac). Anyway, Maven Compiler generates the class file via ASM and the initial class file generator had a bug, using the OS default file separator instead of following the JVM spec and always use `/`, also on Windows.

**Comment by turbanoff** [comment]
Wow. Amazing investigation!
I haven't had time to validate the AspectJ fix. I agree that it's better to revert the fix from AspectJ repo.
Updating maven-compiler-plugins seems helps.

Thanks a lot :)

**Comment by kriegaex** [comment]
I pushed the obsolete commit to a separate branch for reference, just in case someone wants to look at it again in the future.

**Comment by michael-o** [comment]
I tripped over this as well. Is there a portable solution to this since {{-X}} isn't portable...? Willing to change the plugin for the better.
