### ISSUE TITLE
Apache-1.1 license obligations

### ISSUE THREAD

**Issue by waynebeaton** [eclipse-aspectj/aspectj#185]
The project has some content that is under the Apache-1.1 license (see [org.aspectj.apache/bcel/Repository.java](https://github.com/eclipse/org.aspectj/blob/master/bcel-builder/src/main/java/org/aspectj/apache/bcel/Repository.java)).

According to the Apache-1.1 license:

> Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

AFAICT, this means that the license text in its entirety needs to be included in any JAR files that include Apache-1.1 content (e.g., the `aspectjweaver.jar` file).

Further, end user documentation needs to include a statement:

````
 * 3. The end-user documentation included with the redistribution,
 *    if any, must include the following acknowledgment:
 *       "This product includes software developed by the
 *        Apache Software Foundation (http://www.apache.org/)."
 *    Alternately, this acknowledgment may appear in the software itself,
 *    if and wherever such third-party acknowledgments normally appear.
````

I believe that including the statement in the README probably gets us there.

Can a committer please make these changes in time for your next release? I do not believe that there is any need to go back and "fix" any existing releases.

**Comment by kriegaex** [comment]
Thanks for bringing up this issue. The AspectJ project does, however, acknowledge the use of BCEL, also mentioning its licence:

https://github.com/eclipse/org.aspectj/blob/67b1c353a02c335074a736ebf76a49bf24eefb19/docs/dist/LICENSE-AspectJ.html#L41-L46

Would that satisfy your requirement, or is there still a gap?

**Comment by kriegaex** [comment]
I just checked. This licence file has always been part of the AspectJ installer download until version 1.9.6 (inclusive), which you can verify by downloading and installing AspectJ from https://www.eclipse.org/aspectj/. As of 1.9.7, this is no longer true, because after some Maven-related changes, we no longer build the product in the same way. It is my own oversight that I omitted the licence file as part of the documentation, which I no longer generated into the installer package, because I think that the online documentation is just fine. I am going to make sure that the licence file is going to be part of future releases again. Would it suffice to put the licence file into the installer package, or does it need to be part of all public artifacts, such as AspectJ runtime, weaver and tools?

**Comment by waynebeaton** [comment]
Thanks for your prompt attention.

I'm sorry that I missed the reference in the documentation. So that should cover that.

My interpretation of the license is that it should be in all public artifacts. Ideally, somebody obtaining a JAR file from Maven Central should get the license.
