### ISSUE TITLE
Parsing https://www.eclipse.org/aspectj/dtd/aspectj.dtd file fails

### ISSUE THREAD

**Issue by omeraha** [eclipse-aspectj/aspectj#191]
Hi all,
Seems like `https://www.eclipse.org/aspectj/dtd/aspectj.dtd` has changed, and now failed to be parsed (see details [here](https://stackoverflow.com/questions/74158534/aop-is-failing-while-build-sbt-assembly))
The actual error is:
```
org.xml.sax.SAXParseExceptionpublicId: -//AspectJ//DTD//EN; systemId: http://www.eclipse.org/aspectj/dtd/aspectj.dtd; lineNumber: 1; columnNumber: 2; The markup declarations contained or pointed to by the document type declaration must be well-formed.
```

**Comment by kriegaex** [comment]
The DTD has not changed. Maybe the Eclipse website or the parsing tool you use no longer support unencrypted HTTP connections. If I open the file on the browser, I see an HTTPS URL. Maybe your tool does not support redirects or something. Like others said already on Stack Overflow, try HTTPS instead of HTTP. I am closing this issue as invalid, but feel free to comment if you disagree, then I might consider reopening it.
