### ISSUE TITLE
@DeclareMixin introduces a race condition

### ISSUE THREAD

**Issue by zenbones** [eclipse-aspectj/aspectj#198]
When using @DeclareMixin you provide a static method for returning a new instance of the mixed in type. Further annotations provide that mixed in instance to methods via 'this(<mixed in type>)' in the point cut. In the methods on which the point cut operates you get code like...

```
public void someAspectedMethod () {

if (injectedFieldReferenceToMixedInType == null) {
  injectedFieldReferenceToMixedInType = callToMixedInGeneratorDeclaredAs@DeclareMixin();
}

  ...
  original code of method which presumable uses the mixed in type
  ...
}
```

This code injects a race condition where 2 different threads calling two point cut methods using the mixed in type can get 2 different instances of the mixed in type. The injected field is overwritten by one of those calls because the setting of the injected field is not synchronized. Properly, the field should not be directly set in the methods the point cut operates on, instead a new synchronized method should be added to the class which checks if the injected field is null and calls the mix in generator, and that is method which should be called in the point cut altered code. Either that or the injected field should be declared volatile, such that the null check is no longer a race condition.

**Comment by kriegaex** [comment]
@zenbones, Andy as a project lead is basically inactive due to his daytime job, and the situation is not much better on my part. You would help me get started and save some cycles by providing a test which reproduces the race condition. All things related to byte code generation are not my strong suit anyway, so usually I am reluctant to touch that stuff. But a reproducer might encourage me to take a closer look.
