### ISSUE TITLE
update website on eclipse.org

### ISSUE THREAD

**Issue by sellersj** [eclipse-aspectj/aspectj#236]
The official (?) website looks out of date with the latest news / releases being from 2021.
https://www.eclipse.org/aspectj/

If this site has more up to date releases / news that people should be using, the site should point here.

**Comment by kriegaex** [comment]
Yes, that is right. The reason is very simple: Currently, I am the main contributor to AspectJ, but I am not the project lead and do not have write access to all of the project's infrastructure. The project lead, however, does not have any free cycles for AspectJ. I am 95% done migrating all of the existing documentation to AsciiDoc format for it to be readable inline while browsing the repository, see [this branch on my private fork](https://github.com/kriegaex/aspectj/tree/docs-to-asciidoc) and https://github.com/eclipse-aspectj/aspectj/issues/76. Open the issue and click on a few links there in order to inspect the status quo.

@aclement, can you maybe contact me on Slack and tell me how to publish the classical website? Maybe in this case, I have the necesary access rights already, or there is an Eclipse Jenkins job already which I am unaware of. I never really bothered to inquire, because you used to be the person cutting releases and updating the website.

**Comment by kriegaex** [comment]
The website has been updated.
