### ISSUE TITLE
Java 15 support and v1.9.7 release date

### ISSUE THREAD

**Issue by eli-fin** [eclipse-aspectj/aspectj#31]
Hi,

1. As of now, the latest release is 1.9.6, which supports Java 14. When will support for Java 15 be available?
2. In general, how long does it take AspectJ to support a new Java version?
3. When is the release of 1.9.7 planned for?

Thanks

**Comment by aclement** [comment]
Hey,

I'm not sure on the timeframe for Java 15 - do you need something specific out of Java15? Or just generally want to be on the latest? Given the rapid speed of Java releases now it is hard to keep up.

The timeframe following a version can vary a lot. Someone right now is trying to help automate the process to speed it up - currently it is very manual, when it could really be within hours/days of JDT supporting it (as long as the language did not change too much). But even if the result of the attempt to automate is actually writing down the process clearly, I think that would be a massive assist and enable anyone to contribute an upgrade PR. 

I don't have a date scheduled for 1.9.7. I've been wondering about just supporting LTS versions because of the work involved, which would mean Java17 due later in 2021. As far as I'm aware you are the first person to ask for Java15. Right now with 16 due this month, it's hard to justify doing 15 now then repeating it all for 16.

**Comment by eli-fin** [comment]
Was just asking in general. I haven't found anything specific not supported in Java 15.
Thanks for the answer.
