### ISSUE TITLE
Android development environment, using kotlin language, gradle 8.0 or above, how to integrate. I found that it is currently only for java, and there is no integration documentation for it at the moment

### ISSUE THREAD

**Issue by fengchenqixia** [eclipse-aspectj/aspectj#311]
Can you give a new version of the Androy De Kotlin integration documentation

**Comment by kriegaex** [comment]
Sorry, I have no idea what you want. I am closing this issue as invalid. Feel free to edit the issue, providing a comprehensible description and a title summarising the topic. Then, I might reopen it.

**Comment by fengchenqixia** [comment]
Android 开发环境，使用kotlin语言，gradle8.0以上，如何去集成。我发现目前只针对java

**Comment by fengchenqixia** [comment]
Android development environment, using kotlin language, gradle 8.0 or above, how to integrate. I found that it is currently only for java, and there is no integration documentation for it at the moment

**Comment by kriegaex** [comment]
Thanks for the clarification. Please note, that this is an issue tracker for bugs and feature requests, not a support channel. Your question would be better suited on Stack Overflow or the AspectJ users mailing list.

Anyway, the AspectJ source code compiler only understands Java and native AspectJ syntax, because it is derived from the Eclipse Java compiler. But you can use post-compile weaving to instrument byte code created by other JVM languages, such as Kotlin. Please consult the AspectJ documentation. As you are a Gradle user, you might want to use [Freefair plugin's post-compile option](https://docs.freefair.io/gradle-plugins/8.4/reference/#_post_compile_weaving). Good luck.
