### ISSUE TITLE
AspectJ breaks reproducible builds w/JDK 22

### ISSUE THREAD

**Issue by lprimak** [eclipse-aspectj/aspectj#313]
Hi,

It is no longer possible to build to be reproduced on JDK 22 w/AspectJ.

See https://github.com/apache/shiro/issues/1574 for more details

**Comment by lprimak** [comment]
Unable to reproduce

**Comment by kriegaex** [comment]
@lprimak, like this, I would have closed the issue anyway. Even the link tells me nothing about how to even begin trying to reproduce the issue. Please, next time make sure you provide a comprehensive issue description and a minimal reproducer, even if in the end the issue might prove not to have been caused by AspectJ. Either way, a well-described issue is more helpful than this one here.

Thanks for following up and closing the issue by yourself. I hope that you will be able to find out what happens in Shiro. 🙂

**Comment by lprimak** [comment]
Well, what do you know :)
This issue turned out to be valid after all. Created a follow-up issue in #362.

**Comment by kriegaex** [comment]
@lprimak, you had written two years ago:

> Unable to reproduce

That is the reason why this issue was closed as invalid. It is quite hard to fix an issue which is not even reproducible. Now that you found a way to reproduce it and even pinpoint a likely root cause, the new issue #362 is, of course, most welcome. 👏☺️
