### ISSUE TITLE
Missing guidance in release instructions

### ISSUE THREAD

**Issue by aclement** [eclipse-aspectj/aspectj#71]
- it doesn't tell you how to setup your sonatype creds for publishing snapshots

- I don't know how to consume where it is publishing the snapshot, what maven repo would I setup in a project to test it?

**Comment by kriegaex** [comment]
Actually, I thought that was common knowledge or can be easily obtained from other sources, but it is good to have it in the guide, too. But why did you add the `pluginRepository` section? In order to consume AspectJ, it is not necessary. It would help to consume an AspectJ Maven Plugin snapshot, though. Was that the rationale?

**Comment by aclement** [comment]
I still seem to need it in my Spring Roo sample that I have used for many years.

**Comment by kriegaex** [comment]
If you need it there, then not for AspectJ but in order to use the snapshot of a plugin outside of the AspectJ realm. If you cannot find out or are too busy to, I can help you with that, if you can give me access to your sample project. AspectJ is not a Maven plugin, therefore this setting is unnecessary. Besides, since Sonatype introduced a new snapshot URL for new group IDs a while ago, depending on what you want to consume, there are two possible URLs. E.g.
  * `org.aspectj` → `https://oss.sonatype.org/content/repositories/snapshots`
  * `dev.aspectj` → `https://s01.oss.sonatype.org/content/repositories/snapshots`

I have no idea why Sonatype did that instead of solving the problem with a load balancer or so, but they did. So nowadays you need to add different snapshot repositories, depending on what you want to deploy or consume, see for example [my AspectJ Maven fork](https://github.com/dev-aspectj/aspectj-maven-plugin/blob/1f2cf3881662d194e651ba00af4114aa89b91fe2/pom.xml#L64-L67).

Anyway, we should not irritate users and remove the plugin repository section again. I am going to prepare a little PR containing some cosmetic stuff.
