### ISSUE TITLE
Review/port performance enhancements proposed in bugzilla issue

### ISSUE THREAD

**Issue by aclement** [eclipse-aspectj/aspectj#9]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=565450 which includes the patch.

**Comment by LifeIsStrange** [comment]
Any update? This seems like a potentially big improvement

**Comment by aclement** [comment]
Unfortunately haven't had time to do it, but if someone wants to turn it into a PR with maybe a system property to control the behaviour, that would be a likely way for it to go in with limited testing (so by default you get todays behaviour, but switch on a property and this feature could be tested out).

**Comment by kriegaex** [comment]
Because the commits were directly on master and do not come from PR #37, let me mention for reference that @aclement added these changes: https://github.com/eclipse/org.aspectj/compare/1b3cead1715c...3227aad604f0 which are probably going to superseed the PR and eventuall close this issue. Andy was also so kind to add basic tests. 😊

**Comment by kriegaex** [comment]
**To do:** Mention the new options in the 1.9.8 release notes and wherever else it might make sense to integrate them into existing documentation.

**Comment by aclement** [comment]
I think yes to release notes, obviously, but also it needs its own post on the mailing list to raise awareness for anyone that wants to try this out and see if it helps them. I'm not sure where else we could publicize it - [my AspectJ blog](http://andrewclement.blogspot.com) is rather long in the tooth now.

**Comment by kriegaex** [comment]
@aclement: Release notes done, see #116.
